 //--------------------------------------------------------------------------------------
//         COPYRIGHT(C) 2006 Beijing xingdahao technology Co., Ltd.
//                     ALL RIGHTS RESERVED 
//  Project Number: sewing_machine_controller 
//  File Name : common.h
//  Description: common constants definition 
//  Version    Date     Author    Description
//  0.01     23/07/09    zx        created
//  ...
//--------------------------------------------------------------------------------------
#ifndef DS28E01_100_H
#define DS28E01_100_H

extern void OW_check(void);
extern void OW_status(void);
extern void OW_random(void);

#endif